name: siakad_projek
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  

  provider: ^6.1.1
  
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  pdf: ^3.10.7
  printing: ^5.11.1
  fl_chart: ^0.68.0
  flutter_local_notifications: ^17.0.0 # Added for local notifications
  
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  
  
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:


  uses-material-design: true

